org: jefft
app: gh-serverless-s3ocr
service: tesseract-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  deploymentBucket: lambda-layers-mct

layers:
  tesseract:
    path: layer
    compatibleRuntimes:
      - nodejs12.x
resources:
  Outputs:
    TesseractLayerExport:
      Value:
        Ref: TesseractLambdaLayer
      Export:
        Name: TesseractLambdaLayer
